version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: ''

volumes:
  mysql:

networks:
  default: