version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "nT9vR6tv"
      MYSQL_USER: 'rhapsody'
      MYSQL_PASSWORD: 'nT9vR6tv'
      MYSQL_DATABASE: 'rhapsody'

volumes:
  mysql:

networks:
  default: